Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [3]:
import numpy as np

In [4]:
N = 10
x = np.full(N, N)
y = np.arange(1, N+1)
x - y

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [5]:
N = 15
M = np.diag(np.arange(N, -1, -5), k = 0)
M

array([[15,  0,  0,  0],
       [ 0, 10,  0,  0],
       [ 0,  0,  5,  0],
       [ 0,  0,  0,  0]])

In [6]:
summ = 0
index = 0
for i in M:
    summ += i[index]
    index += 1
print(summ) 

30


Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [7]:
a = np.array([[4, 2, 2], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

In [8]:
from numpy import linalg

In [9]:
linalg.solve(a, b)

array([ 1.8,  3.4, -5. ])

In [10]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

Задача 4 домашнего задания
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [11]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [12]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [13]:
def cosine(user, next_user_stats):
        user_len = np.linalg.norm(user)
        next_user_stats_len = np.linalg.norm(next_user_stats)
        return np.dot(user, next_user_stats)/(user_len * next_user_stats_len)

In [14]:
corr = np.array([cosine(user, next_user_stats) for user in users_stats])
corr

array([0.2       , 0.84515425, 0.4       , 0.79056942, 0.4       ,
       0.        , 0.        , 0.9486833 , 0.        , 0.        ])

User с id=8 наиболее схож с новым посетителем next_user_stats.